language: node_js
	node_js:
	- "4"  # nodejs的版本
	branches:
	  only:
	  - master  # 设置自动化部署的源码分支
	env:
	  global:
	    secure: github.com/jilei6/jilei6.github.io
	before_install:
	- export TZ='Asia/Shanghai'  # 设置时区
	- cnpm install -g hexo
	- cnpm install -g hexo-cli
	before_script:
	# 设置github账户信息
	- git config --global user.name "jilei6" #设置github用户名
	- git config --global user.email 434450279@qq.com #设置github用户邮箱
	# github仓库操作
	- sed -i'' "s~git@github.com:jilei6/jilei6.github.io.git~https://${testTravisCI}:x-oauth-basic@github.com/jilei6/jilei6.github.io.git~" _config.yml
	# 安装依赖组件
	install:
	- cnpm install
	# 执行的命令
	script:
	- hexo clean
	- hexo generate
	# 执行的成功后执行 
	after_success:
	- hexo deploy
