language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install


#before_script:
 # - npm install -g gulp

script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "jilei6"
  - git config user.email "434450279@qq.com"
  - git add .
  - git commit -m "testTravisCI"
  - git push --force --quiet "https://${testTravisCI}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - master
env:
 global:
   - GH_REF: github.com/jilei6/jilei6.github.io.git
