language: node_js

node_js:

- '8'

branches:

  only:

  - master

env:

 global: github.com/jilei6/jilei6.github.io

 secure: ""
before_install:

- export TZ='Asia/Shanghai'

- npm install -g hexo

- npm install -g hexo-cli

before_script:

- git config --global user.name "jilei6"

- git config --global user.email 434450279@qq.com


install:

- npm install

script:

- hexo clean

- hexo generate

after_success:

- hexo deploy

