language: node_js
node_js:
- '8'
branches:
  only:
  - master
env:
 global: github.com/jilei6/jilei6.github.io
 secure: "IV6c/PzKSlUrhGmjH3EWjYmZzPcmBdsSbwFuMvQDM9N8druWBza98YPPw+TfTPYCUfWArZPHtTBRX3PN+vkBUv3UcQbOuEcOz5jxN8Hww9MfwZXlE5yGTwdLObdfYSQq2RoQ0gRmBFL6hA9ooc7iWeW9SlKuO/6tvcl0atDxG3cXCDw9O9VNg2pqTK2DdGipnHYI3KUH/0Rl87Z3aNblS75WaTpRYdl0c3aYu/nO/QY5rUl6HhT7EsfFH10Bz/NIhVH3tc7XDxCxDQPUc7AHx/pnJVmMZOG8oHn9yHkf3tQrWbmkBYNJ8aJEgsItfhczLcdePf/f9fAmqJX4MmzhyF7GohJM5NE19yOjP4H3zFViyXbJnNgQ2FR4Cbonq/SQOe3mAd+JfhLTbnpjygugI8AwMyjTAFwvBYJgaEdbRHmQQ/jDA8ewb1d4wEO7CAVYUbArIKPZpiRcaQcsGFfruOsx2Hh8ACkMWD/4xWZLz8M7+FIU5UIa72mPtz2tafuNEXGNu7sBGSzE/O7F+sLnUMhx0/M3r67nqtbVilSWpLTXIlmeoxTfR400pEcRzF0kxW+c3zaqsjIE4v5gZmGHNeD8IZqS5sLqKSMmQnRV12jSuLjANbv1nNt7hf4D6Fb6IEp6jJGAzq9YImwtz9352buiozirOJsNKQG1WBNPddQ="
before_install:
- export TZ='Asia/Shanghai'
- npm install -g hexo
- npm install -g hexo-cli
before_script:
- git config --global user.name "jilei6"
- git config --global user.email 434450279@qq.com
- sed -i'' "s~git@github.com:jilei6/jilei6.github.io.git~https://${testTravisCI}:x-oauth-basic@github.com/jilei6/jilei6.github.io.git~" _config.yml
install:
- npm install
script:
- hexo clean
- hexo generate
after_success:
- hexo deploy
